### ISSUE TITLE
[Android Bootcamp] Project 2 - Review my app

### ISSUE THREAD

**Issue by simonque** [simonque/ImageFinder#1]
I've done all the required stories and two optional stories.

/cc @nesquena @thecodepath

**Comment by vibhorB** [comment]
Good work Simon. A few notes after checking out the code:
- Good to see you added Share action in full image activity
- Properly reused the single base method in search activity to fetch results for both initial load and the pagination
- Properly used spinners (with populated values) to allow users to select filters
- Good way of making SearchOptions Serializable so that you don't need to pass multiple keys
- Good job with error handling
- An activity should be named as SettingsActivity and not just Settings
- Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)

Also, here's a more detailed [Project 2 Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](https://gist.github.com/nesquena/44091e4727b154d04269) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
